; test ini for ConfigLoadHarness
[Startup]

[Map]
WorldMapModule = "WorldMap"
MapImageModule = "Warp3DImageModule"
TilesStoragePath = "legacy-maptiles"

[MapImageService]
TilesStoragePath = "canonical-maptiles"

[GridService]
HypergridLinker = true
MapTileDirectory = "legacy-hg-maptiles"

[Hypergrid]
GatekeeperURI = "http://localhost:8002/"
HomeURI = "http://localhost:8002/"
